[package]
name = "transportation"
version = "5.1.0"
authors = ["Jenna Magius <pyrosim@gmail.com>"]
license = "BSD-2-Clause"
description = "A callback wrapper around MIO"
repository = "https://github.com/oxy-secure/transportation"

[dependencies]
mio = "0.6"
lazy_static = "1"
